//
//  Globals.swift
//  DEPNotify Set-up Helper
//
//  Created by Leslie Helou on 2/25/20.
//  Copyright © 2020 Leslie Helou. All rights reserved.
//

struct policy {
    static var attributeDict = [String:[String:String]]()
    static var runList       = ""
}

struct keys {
    
    static var settingsDict = [String:String]()
    
    // TRIGGER has been removed
    static var nameArray = ["TESTING_MODE",
                            "FULLSCREEN",
                            "BANNER_IMAGE_PATH",
                            "BANNER_TITLE",
                            "MAIN_TEXT",
                            "INITAL_START_STATUS",
                            "INSTALL_COMPLETE_TEXT",
                            "COMPLETE_METHOD_DROPDOWN_ALERT",
                            "FV_ALERT_TEXT",
                            "FV_COMPLETE_MAIN_TEXT",
                            "FV_COMPLETE_BUTTON_TEXT",
                            "COMPLETE_ALERT_TEXT",
                            "COMPLETE_MAIN_TEXT",
                            "COMPLETE_BUTTON_TEXT",
                            "STATUS_TEXT_ALIGN",
                            "HELP_BUBBLE_TITLE",
                            "HELP_BUBBLE_BODY",
                            "ERROR_BANNER_TITLE",
                            "ERROR_MAIN_TEXT",
                            "ERROR_STATUS",
                            "POLICY_ARRAY",
                            "NO_SLEEP",
                            "SELF_SERVICE_CUSTOM_BRANDING",
                            "SELF_SERVICE_APP_NAME",
                            "EULA_ENABLED",
                            "EULA_STATUS",
                            "EULA_BUTTON",
                            "EULA_MAIN_TITLE",
                            "EULA_SUBTITLE",
                            "EULA_FILE_PATH",
                            "REGISTRATION_ENABLED",
                            "REGISTRATION_TITLE",
                            "REGISTRATION_STATUS",
                            "REGISTRATION_BUTTON",
                            "REGISTRATION_BEGIN_WORD",
                            "REGISTRATION_MIDDLE_WORD",
                            "REG_TEXT_LABEL_1",
                            "REG_TEXT_LABEL_1_PLACEHOLDER",
                            "REG_TEXT_LABEL_1_OPTIONAL",
                            "REG_TEXT_LABEL_1_HELP_TITLE",
                            "REG_TEXT_LABEL_1_HELP_TEXT",
                            "REG_TEXT_LABEL_2",
                            "REG_TEXT_LABEL_2_PLACEHOLDER",
                            "REG_TEXT_LABEL_2_OPTIONAL",
                            "REG_TEXT_LABEL_2_HELP_TITLE",
                            "REG_TEXT_LABEL_2_HELP_TEXT",
                            "REG_POPUP_LABEL_1",
                            "REG_POPUP_LABEL_1_OPTIONS",
                            "REG_POPUP_LABEL_1_HELP_TITLE",
                            "REG_POPUP_LABEL_1_HELP_TEXT",
                            "REG_POPUP_LABEL_2",
                            "REG_POPUP_LABEL_2_OPTIONS",
                            "REG_POPUP_LABEL_2_HELP_TITLE",
                            "REG_POPUP_LABEL_2_HELP_TEXT",
                            "REG_POPUP_LABEL_3",
                            "REG_POPUP_LABEL_3_OPTIONS",
                            "REG_POPUP_LABEL_3_HELP_TITLE",
                            "REG_POPUP_LABEL_3_HELP_TEXT",
                            "REG_POPUP_LABEL_4",
                            "REG_POPUP_LABEL_4_OPTIONS",
                            "REG_POPUP_LABEL_4_HELP_TITLE",
                            "REG_POPUP_LABEL_4_HELP_TEXT",
                            "JAMF_BINARY",
                            "FDE_SETUP_BINARY",
                            "DEP_NOTIFY_APP",
                            "DEP_NOTIFY_LOG",
                            "DEP_NOTIFY_DEBUG",
                            "DEP_NOTIFY_DONE",
                            "DEP_NOTIFY_EULA_DONE",
                            "DEP_NOTIFY_REGISTER_DONE",
                            "ADDITIONAL_OPTIONS_COUNTER"]
    
    static var namesDictionary = ["TESTING_MODE":"Testing Mode",
                                    "FULLSCREEN":"Full Screen",
                                    "BANNER_IMAGE_PATH":"Banner Image Path",
                                    "BANNER_TITLE":"Banner Title",
                                    "MAIN_TEXT":"Main Text",
                                    "INITAL_START_STATUS":"Initial Start Status",
                                    "INSTALL_COMPLETE_TEXT":"Install Complete Text",
                                    "COMPLETE_METHOD_DROPDOWN_ALERT":"Complete Method Dropdown Alert",
                                    "FV_ALERT_TEXT":"FV Alert Text",
                                    "FV_COMPLETE_MAIN_TEXT":"FV Complete Main Text",
                                    "FV_COMPLETE_BUTTON_TEXT":"FV Complete Button Text",
                                    "COMPLETE_ALERT_TEXT":"Complete Alert Text",
                                    "COMPLETE_MAIN_TEXT":"Complete Main Text",
                                    "COMPLETE_BUTTON_TEXT":"Complete Button Text",
                                    "STATUS_TEXT_ALIGN":"Status Text Align",
                                    "HELP_BUBBLE_TITLE":"Help Bubble Title",
                                    "HELP_BUBBLE_BODY":"Help Bubble Body",
                                    "ERROR_BANNER_TITLE":"Error Banner Title",
                                    "ERROR_MAIN_TEXT":"Error Main Text",
                                    "ERROR_STATUS":"Error Status",
                                    "POLICY_ARRAY":"Policy Array",
                                    "NO_SLEEP":"No Sleep",
                                    "SELF_SERVICE_CUSTOM_BRANDING":"Self Service Custom Branding",
                                    "SELF_SERVICE_APP_NAME":"Self Service App Name",
                                    "EULA_ENABLED":"EULA Enabled",
                                    "EULA_STATUS":"EULA Status",
                                    "EULA_BUTTON":"EULA Button",
                                    "EULA_MAIN_TITLE":"EULA Main Title",
                                    "EULA_SUBTITLE":"EULA Subtitle",
                                    "EULA_FILE_PATH":"EULA File Path",
                                    "REGISTRATION_ENABLED":"Registration Enabled",
                                    "REGISTRATION_TITLE":"Registration Title",
                                    "REGISTRATION_STATUS":"Registration Status",
                                    "REGISTRATION_BUTTON":"Registration Button",
                                    "REGISTRATION_BEGIN_WORD":"Registration Begin Word",
                                    "REGISTRATION_MIDDLE_WORD":"Registration Middle Word",
                                    "REG_TEXT_LABEL_1":"Registration Text Label 1",
                                    "REG_TEXT_LABEL_1_PLACEHOLDER":"Registration Text Label 1 Placeholder",
                                    "REG_TEXT_LABEL_1_OPTIONAL":"Registration Text Label 1 Optional",
                                    "REG_TEXT_LABEL_1_HELP_TITLE":"Registration Text Label 1 Help Title",
                                    "REG_TEXT_LABEL_1_HELP_TEXT":"Registration Text Label 1 Help Text",
                                    "REG_TEXT_LABEL_2":"Registration Text Label 2",
                                    "REG_TEXT_LABEL_2_PLACEHOLDER":"Registration Text Label 2",
                                    "REG_TEXT_LABEL_2_OPTIONAL":"Registration Text Label 2 Optional",
                                    "REG_TEXT_LABEL_2_HELP_TITLE":"Registration Text Label 2 Title",
                                    "REG_TEXT_LABEL_2_HELP_TEXT":"Registration Text Label 2 Text",
                                    "REG_POPUP_LABEL_1":"Registration Popup Label 1",
                                    "REG_POPUP_LABEL_1_OPTIONS":"Registration Popup Label 1 Options",
                                    "REG_POPUP_LABEL_1_HELP_TITLE":"Registration Popup Label 1 Help Title",
                                    "REG_POPUP_LABEL_1_HELP_TEXT":"Registration Popup Label 1 Help Text",
                                    "REG_POPUP_LABEL_2":"Registration Popup Label 2",
                                    "REG_POPUP_LABEL_2_OPTIONS":"Registration Popup Label 2 Options",
                                    "REG_POPUP_LABEL_2_HELP_TITLE":"Registration Popup Label 2 Help Title",
                                    "REG_POPUP_LABEL_2_HELP_TEXT":"Registration Popup Label 2 Help Text",
                                    "REG_POPUP_LABEL_3":"Registration Popup Label 3",
                                    "REG_POPUP_LABEL_3_OPTIONS":"Registration Popup Label 3 Options",
                                    "REG_POPUP_LABEL_3_HELP_TITLE":"Registration Popup Label 3 Help Title",
                                    "REG_POPUP_LABEL_3_HELP_TEXT":"Registration Popup Label 3 Help Text",
                                    "REG_POPUP_LABEL_4":"Registration Popup Label 4",
                                    "REG_POPUP_LABEL_4_OPTIONS":"Registration Popup Label 4 Options",
                                    "REG_POPUP_LABEL_4_HELP_TITLE":"Registration Popup Label 4 Help Title",
                                    "REG_POPUP_LABEL_4_HELP_TEXT":"Registration Popup Label 4 Help Text",
                                    "JAMF_BINARY":"Jamf Binary",
                                    "FDE_SETUP_BINARY":"FDE Setup Binary",
                                    "DEP_NOTIFY_APP":"DEPNotify Application",
                                    "DEP_NOTIFY_LOG":"DEPNotify Log",
                                    "DEP_NOTIFY_DEBUG":"DEPNotify Debug",
                                    "DEP_NOTIFY_DONE":"DEPNotify Done",
                                    "DEP_NOTIFY_EULA_DONE":"DEPNotify EULA Done",
                                    "DEP_NOTIFY_REGISTER_DONE":"DEPNotify Registration Done",
                                    "ADDITIONAL_OPTIONS_COUNTER":"Additional Options Counter"]
}
